import { useRouter } from "next/router";
import Head from "next/head";

const Randomer = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>{router.query.id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Welcome to this yoke, starring {router.query.id}!</div>
    </>
  );
};

export default Randomer;
